apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k8kytc4fx-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6351d701f2.zq1g.p3.openshiftapps.com/rhtap/rhtap-qe:f3dc93bd4b123803308afa80e4ad7551b4e6a598@sha256:9a54f4fecee81ec0d4576725141adb9c4bc7865f37a04296e0890b68ef2541e4
          name: container-image
